services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8080
    depends_on:
      backend:
        condition: service_started
    command: npm run dev -- --host 0.0.0.0

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    environment:
      - PORT=8080
    depends_on:
      database:
        condition: service_started

  database:
    image: postgres:16-alpine
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: manage_finances
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./database-data:/var/lib/postgresql

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8090:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - database