-- +goose Up

CREATE TABLE categories (
    -- category_id follows transactions.transaction_id's shape, not
    -- accounts.account_id's: like a transaction, a category row is never
    -- addressed by id from outside this package.
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL,
    -- 50 matches transactions.category's width, so a name that fits one
    -- fits the other.
    name VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_categories_user
        FOREIGN KEY (uuid)
        REFERENCES users(uuid)
        ON DELETE CASCADE
);

-- Named explicitly (not left to a generated name) because the verification
-- gates and \d categories both reference categories_uuid_name_lower_key by
-- name. This expression index, not application code, is what makes the
-- case-insensitive dedup a storage-level guarantee: it is the backstop if
-- two requests race between resolveCategory's lookup and its insert.
CREATE UNIQUE INDEX categories_uuid_name_lower_key ON categories (uuid, lower(name));

-- Seeds the users that existed when this table shipped. New users are
-- seeded by defaultCategories in repository.go -- the two lists must be
-- changed together.
INSERT INTO categories (uuid, name)
SELECT u.uuid, seed.name
FROM users u
CROSS JOIN (VALUES
    ('Groceries'),
    ('Housing'),
    ('Transportation'),
    ('Utilities'),
    ('Entertainment'),
    ('Health'),
    ('Dining'),
    ('Savings')
) AS seed(name);

-- +goose Down

DROP TABLE categories;
